CREATE TABLE ACCOUNT (
	USERNAME VARCHAR(40) PRIMARY KEY,
	FULLNAME VARCHAR(40),
	BIRTH DATETIME,
	SEX CHAR(1),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(40),
	PASSWORD VARCHAR(20),
	AVATAR VARCHAR(200),
	NUM_POST INT,
	NUM_FOLLOWER INT,
	NUM_FOLLOW INT,
	CAPTION VARCHAR(200),
)

UPDATE ACCOUNT SET NUM_POST=0 WHERE USERNAME='havold'

SELECT MAPOST,CAPTION,TIMEPOST,USERNAME,NUM_CMT,NUM_LIKE,NUM_IMAGE FROM POST WHERE MAPOST='\_e]zHYdEK'

DELETE FROM ACCOUNT WHERE USERNAME='havol'

SELECT * FROM ACCOUNT

DROP TABLE ACCOUNT

CREATE TABLE POST (
	MAPOST VARCHAR(10) PRIMARY KEY,
	CAPTION VARCHAR(200),
	TIMEPOST DATETIME,
	USERNAME VARCHAR(40),
	NUM_CMT INT,
	NUM_LIKE INT,
	NUM_IMAGE INT,
)

SELECT * FROM POST

SELECT COUNT(*) FROM POST

DROP TABLE POST

CREATE TABLE IMAGEPOST(
	IMAGEPATH VARCHAR(40),
	MAPOST VARCHAR(10),
)

SELECT * FROM IMAGEPOST

DROP TABLE IMAGEPOST


CREATE TABLE COMMENT (
	MACMT VARCHAR(10),
	USERNAME_CMT VARCHAR(40),
	CONTENT VARCHAR(40),
	MAPOST VARCHAR(10),
	USER_POST VARCHAR(40),
	TIMECMT DATETIME,
	SEEN CHAR(1),
)


SELECT * FROM COMMENT 

SELECT MACMT,USERNAME_CMT,CONTENT,TIMECMT FROM COMMENT WHERE MAPOST = 'RKbGJxchuC' ORDER BY TIMECMT DESC

DROP TABLE COMMENT


CREATE TABLE LIKE_STATUS (
	USERNAME_LIKE VARCHAR(40),
	MAPOST VARCHAR(10),
	USER_POST VARCHAR(40),
	TIME_LIKE DATETIME,
	SEEN CHAR(1)
)

SELECT * FROM LIKE_STATUS

DROP TABLE LIKE_STATUS


CREATE TABLE NOTIFICATION (
	MANOTI VARCHAR(10) PRIMARY KEY,
	TIMENOTI DATETIME,
	LOAINOTI CHAR(1),
	MAPOST VARCHAR(10),
	CONTENT VARCHAR(40),
	USERNAME_NOTI CHAR(40),
)

DROP TABLE NOTIFICATION


SELECT * FROM ACCOUNT

CREATE TABLE ONLINE (
	USERNAME VARCHAR(40),
	FULLNAME VARCHAR(40),
	TIMEIN DATETIME,
	REMEMBER CHAR(1),
	PASSWORD VARCHAR(20),
	AVATAR VARCHAR(200),
	CAPTION VARCHAR(200),
	NUM_POST INT,
	NUM_FOLLOWER INT,
	NUM_FOLLOW INT,
)

DROP TABLE ONLINE


SELECT * FROM ONLINE

CREATE TABLE REQUEST (
	USER_REQUEST VARCHAR(40),
	USER_REQUESTED VARCHAR(40),
	TIMEREQUEST DATETIME,
	SEEN CHAR(1)
)

SELECT * FROM REQUEST
SELECT * FROM REQUEST WHERE USER_REQUEST='havold' AND USER_REQUESTED='khoane'
INSERT INTO REQUEST VALUES('HAHA','"+usernameGet+"','12/2/2023','N')
INSERT INTO REQUEST VALUES('HAHA','haha','12/2/2023','N')
DROP TABLE REQUEST

CREATE TABLE FOLLOW (
	FOLLOWER VARCHAR(40),
	FOLLOW VARCHAR(40),
	TIMEFOLLOW DATETIME,
	SEEN CHAR(1)
)

DROP TABLE FOLLOW

SELECT * FROM FOLLOW

SELECT * FROM ACCOUNT WHERE USERNAME!='havold'

SELECT * FROM ONLINE

CREATE TABLE Messed (
	Classify VARCHAR(200),
	Text VARCHAR(200),
)

SELECT * FROM Messed

INSERT INTO Messed (Classify, Text) VALUES ('anhtrailonbu-havold', 'anhtrailonbu-hello-D:\\C#\\Instagram\\png\\avatar\\avatar_1.png');

DROP TABLE Messed
